import type { NextPage } from 'next';
import Head from 'next/head';
import { HelpButton } from '../src/components/helpButton';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>👀 Bottom right 👉👇</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HelpButton />
    </>
  );
};

export default Home;
